---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: flux-system
spec:
  limits:
  - default:
      memory: 640Mi
      cpu: 1
    defaultRequest:
      memory: 512Mi
      cpu: 10m
    type: Container
