---
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - name: sonarqube-dce.danil.sonar-dev.shoot.canary.k8s-hana.ondemand.com
      # Different clouds or configurations might need /* as the default path
      path: /
      # For additional control over serviceName and servicePort
      # serviceName: someService
      # servicePort: somePort
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"